services:
  uptimekuma:
    image: louislam/uptime-kuma:latest
    container_name: uptimekuma
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.uptimekuma.rule=Host(`status.${DNS_DOMAIN}`)"
      - "traefik.http.routers.uptimekuma.entrypoints=websecure"
      - "traefik.http.routers.uptimekuma.tls.certresolver=letsencrypt"
      - "traefik.http.services.uptimekuma.loadbalancer.server.port=3001"
      - "traefik.docker.network=traefik-network"
    volumes:
      - uptimekuma_data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    networks:
      - traefik-network
      - prometheus-network
      - loki-network
      - dns-network
      - nextcloud-aio

volumes:
  uptimekuma_data:
    name: uptimekuma_data

networks:
  traefik-network:
    external: true
  prometheus-network:
    external: true
  loki-network:
    external: true
  dns-network:
    external: true
  nextcloud-aio:
    external: true
