services:
  loki:
    image: grafana/loki:latest
    container_name: loki
    volumes:
      - ./loki:/etc/loki
      - loki_data:/tmp/loki
    restart: always
    command: -config.file=/etc/loki/loki.yml
    networks:
      - prometheus-network
      - loki-network

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - /var/log:/var/log:ro
      - /var/log/audit:/var/log/audit:ro
      - /var/log/immich-go:/var/log/immich-go:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./promtail:/etc/promtail
      - promtail_positions:/var/promtail
    restart: always
    command: -config.file=/etc/promtail/promtail.yml
    networks:
      - loki-network

volumes:
  loki_data:
    name: loki_data
  promtail_positions:
    name: promtail_positions

networks:
  prometheus-network:
    external: true
  loki-network:
    external: true
