services:
  server:
    image: "vaultwarden/server:latest"
    container_name: vaultwarden
    volumes:
      - vaultwarden_data:/data/
    restart: unless-stopped
    dns:
      - ${PRIMARY_DNS:-192.168.0.253}
      - ${SECONDARY_DNS:-1.1.1.1}
    networks:
      - traefik-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vaultwarden.rule=Host(`vault.${DNS_DOMAIN}`)"
      - "traefik.http.routers.vaultwarden.entrypoints=websecure"
      - "traefik.http.routers.vaultwarden.tls.certresolver=letsencrypt"
      - "traefik.http.services.vaultwarden.loadbalancer.server.port=80"
      - "traefik.docker.network=traefik-network"

volumes:
  vaultwarden_data:
    name: vaultwarden_data

networks:
  traefik-network:
    external: true
