services:
  diun:
    image: crazymax/diun:latest
    container_name: diun
    command: serve
    restart: always
    volumes:
      - ./composes/diun/config:/etc/diun:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - diun_data:/data
    environment:
      - TZ=Europe/Zurich
      - LOG_LEVEL=info
      - LOG_JSON=false
    dns:
      - ${PRIMARY_DNS:-192.168.0.253}
      - ${SECONDARY_DNS:-1.1.1.1}
    networks:
      - traefik-network

volumes:
  diun_data:
    name: diun_data

networks:
  traefik-network:
    external: true
