services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    volumes:
      - ./composes/homepage/config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - TZ=Europe/Zurich
      - HOMEPAGE_ALLOWED_HOSTS=${DNS_DOMAIN},${DNS_DOMAIN}:443,homepage:3000,homepage,localhost:3000,127.0.0.1:3000
    dns:
      - ${PRIMARY_DNS:-192.168.0.253}
      - ${SECONDARY_DNS:-1.1.1.1}
    networks:
      - traefik-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homepage.rule=Host(`${DNS_DOMAIN}`)"
      - "traefik.http.routers.homepage.entrypoints=websecure"
      - "traefik.http.routers.homepage.tls.certresolver=letsencrypt"
      - "traefik.http.services.homepage.loadbalancer.server.port=3000"
      - "traefik.docker.network=traefik-network"

networks:
  traefik-network:
    external: true
