services:
  bind9:
    container_name: bind9
    image: ubuntu/bind9:latest
    environment:
      - BIND9_USER=root
      - TZ=Europe/Zurich
    ports:
      - "${IP_ADDRESS}:53:53/tcp"
      - "${IP_ADDRESS}:53:53/udp"
    volumes:
      - ./composes/dns/config:/etc/bind/
      - ./composes/dns/cache:/var/cache/bind
      - ./composes/dns/records:/var/lib/bind
    restart: always
    networks:
      dns-network:
        ipv4_address: 172.28.0.53

networks:
  dns-network:
    external: true
